### ISSUE TITLE
Colobot is not appearing in flathub.org because of wrong component type

### ISSUE THREAD

**Issue by jgarciao** [flathub/info.colobot.Colobot#1]
Flathub.org (the website) gets the information about the apps from the appstream.xml file generated in the ostree repo. You can see the contents in your computer opening this file: /var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml

This app is not appearing in the website because it has some issues in the appstream information:

    * `<component type> `should be `<component type="desktop">`

**Comment by ananace** [comment]
Thanks for the report, could you also throw in a PR with the change? Or would you prefer if I do it?

**Comment by jgarciao** [comment]
I'm not familiar with this app so prefer if you do it. Thank you!

**Comment by ananace** [comment]
Just pushed the change.

Let's see if an updated build will help, though I feel like this should probably be caught by the flathub verification builder if it causes the application to completely disappear from the store page.

**Comment by jgarciao** [comment]
I think it was never published in the website because of this

**Comment by ananace** [comment]
Well, the game is visible on flathub.org now, so I'm going to consider this fixed. :+1:

**Comment by jgarciao** [comment]
Thanks!

El dv., 15 de febr. 2019, 20:31, ananace <notifications@github.com> va
escriure:
